version: "3.9"

services:
  db:
    image: postgres:14
    container_name: splitwise_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Akhila@13
      POSTGRES_DB: splitwise_clone
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: splitwise_api
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/app/app


volumes:
  db_data:
